import type { Locale } from "@/lib/i18n/config";
import { resolveAdminCopy } from "@/lib/admin/institutional-admin-copy";

const baseDictionaries = {
  en: {
    title: "Official IKA instructors",
    intro: "Manage the public official instructors directory here. Only the super admin can add, edit, hide, or delete records.",
    categoriesTitle: "IKA official roles",
    categoriesIntro: "Manage official instructors, official examiners, and official judges from this same Super Admin space. Each profile can be published, edited, or reordered independently.",
    categoryInstructors: "Official instructors",
    categoryExaminers: "Official examiners",
    categoryJudges: "Official judges",
    categoryLive: "Active",
    categoryPrepared: "Active",
    categoryFutureNote: "This category is already available so you can start publishing these official figures whenever you need.",
    categoryField: "Category",
    categoryInstructor: "Official instructor",
    categoryExaminer: "Official examiner",
    categoryJudge: "Official judge",
    chiefOnlyForInstructors: "Chief Instructor can only be assigned inside the official instructors category.",
    loginFirst: "Sign in to the admin first to manage instructors.",
    selectPlaceholder: "Select one option",
    name: "Name",
    grade: "Grade",
    country: "Country of origin",
    chiefNote: "Chief instructor note",
    order: "Order",
    visible: "Visible",
    chiefInstructor: "Chief instructor label",
    chiefBadge: "IKA Chief Instructor",
    yes: "Yes",
    no: "No",
    photo: "Photo",
    photoAlt: "Photo alt text",
    previewAlt: "Instructor photo",
    noPhoto: "No photo",
    uploadPhoto: "Upload photo",
    changePhoto: "Change photo",
    removePhoto: "Remove photo",
    saveChanges: "Save changes",
    create: "Create instructor",
    reset: "Reset",
    listTitle: "Current list",
    loading: "Loading instructors...",
    empty: "There are no instructors yet.",
    edit: "Edit",
    delete: "Delete",
    published: "Published",
    hidden: "Hidden",
    required: "Name and country of origin are required.",
    created: "Instructor created.",
    updated: "Instructor updated.",
    deleted: "Instructor deleted.",
    selectImage: "Select a valid image.",
    language: "Language",
    translateChiefNote: "Translate note from Spanish",
    translateChiefNoteHelp: "Write the Chief Instructor note in Spanish first. This button will generate the rest of the languages automatically.",
    chiefNoteNeedsSpanish: "Please write the Chief Instructor note in Spanish first.",
    chiefNoteTranslationReady: "Chief Instructor note translations generated. Now save the changes.",
    chiefNoteTranslationFailed: "Could not translate the Chief Instructor note.",
  },
  es: {
    title: "Instructores oficiales IKA",
    intro: "Gestiona desde aqu\u00ed el listado p\u00fablico de instructores oficiales. Solo el super admin puede a\u00f1adir, editar, ocultar o eliminar fichas.",
    categoriesTitle: "Cargos oficiales IKA",
    categoriesIntro: "Gestiona desde este mismo espacio de Super Admin a los instructores oficiales, examinadores oficiales y jueces oficiales. Cada ficha puede publicarse, editarse y reordenarse de forma independiente.",
    categoryInstructors: "Instructores oficiales",
    categoryExaminers: "Examinadores oficiales",
    categoryJudges: "Jueces oficiales",
    categoryLive: "Activo",
    categoryPrepared: "Activo",
    categoryFutureNote: "Esta categoria ya esta disponible para empezar a publicar estas figuras oficiales cuando lo necesites.",
    categoryField: "Categoria",
    categoryInstructor: "Instructor oficial",
    categoryExaminer: "Examinador oficial",
    categoryJudge: "Juez oficial",
    chiefOnlyForInstructors: "La etiqueta Chief Instructor solo puede asignarse dentro de la categoria de instructores oficiales.",
    loginFirst: "Entra primero en el admin para gestionar instructores.",
    selectPlaceholder: "Selecciona una opcion",
    name: "Nombre",
    grade: "Grado",
    country: "Pa\u00eds de origen",
    chiefNote: "Nota institucional del chief instructor",
    order: "Orden",
    visible: "Visible",
    chiefInstructor: "Etiqueta chief instructor",
    chiefBadge: "IKA Chief Instructor",
    yes: "S\u00ed",
    no: "No",
    photo: "Foto",
    photoAlt: "Texto alternativo de la foto",
    previewAlt: "Foto del instructor",
    noPhoto: "Sin foto",
    uploadPhoto: "Subir foto",
    changePhoto: "Cambiar foto",
    removePhoto: "Quitar foto",
    saveChanges: "Guardar cambios",
    create: "Crear instructor",
    reset: "Limpiar",
    listTitle: "Listado actual",
    loading: "Cargando instructores...",
    empty: "Todav\u00eda no hay instructores cargados.",
    edit: "Editar",
    delete: "Eliminar",
    published: "Publicado",
    hidden: "Oculto",
    required: "Nombre y pa\u00eds de origen son obligatorios.",
    created: "Instructor creado.",
    updated: "Instructor actualizado.",
    deleted: "Instructor eliminado.",
    selectImage: "Selecciona una imagen v\u00e1lida.",
    language: "Idioma",
    translateChiefNote: "Traducir nota desde espa\u00f1ol",
    translateChiefNoteHelp: "Escribe primero la nota del Chief Instructor en espa\u00f1ol. Este bot\u00f3n generar\u00e1 autom\u00e1ticamente el resto de idiomas.",
    chiefNoteNeedsSpanish: "Primero escribe la nota del Chief Instructor en espa\u00f1ol.",
    chiefNoteTranslationReady: "Traducciones de la nota generadas. Ahora solo falta guardar los cambios.",
    chiefNoteTranslationFailed: "No se pudo traducir la nota del Chief Instructor.",
  },
} satisfies Partial<Record<Locale, Record<string, string>>>;

export function getOfficialInstructorsAdminCopy(locale: Locale) {
  return resolveAdminCopy(locale, baseDictionaries);
}

export function getChiefInstructorCopy(locale: Locale) {
  if (locale === "es") {
    return {
      label: "Etiqueta chief instructor",
      badge: "IKA Chief Instructor",
    };
  }

  return {
    label: "Chief instructor label",
    badge: "IKA Chief Instructor",
  };
}
