import type { Locale } from "@/lib/i18n/config";
import { resolveAdminCopy } from "@/lib/admin/institutional-admin-copy";

const dictionaries = {
  en: {
    saved: "Settings saved.",
    selectImageFile: "Select an image.",
    signInFirst: "Sign in to admin first to modify global settings.",
    title: "Carousel speed",
    language: "Language",
    mode: "Mode",
    autoMode: "Automatic, as now",
    manualMode: "Speed chosen by the user",
    latestReportsSeconds: "Latest reports, seconds per loop",
    lowerCarouselSeconds: "Lower carousel, seconds per loop",
    help: "The higher the number, the slower it moves. Automatic mode keeps the current website speed.",
    secretaryTitle: "IKA Secretary General",
    secretaryName: "Name",
    secretaryRole: "Displayed role",
    secretaryText: "Public text",
    secretaryPhoto: "Photo",
    secretaryPhotoAlt: "Photo alt text",
    translateSecretary: "Translate all from Spanish",
    translateSecretaryHelp: "Write the role, public text, and photo alt text in Spanish first. This button will automatically generate the other languages.",
    secretaryTranslationNeedsSpanish: "Please write the Secretary General content in Spanish first.",
    secretaryTranslationReady: "Translations generated. Now save the settings.",
    secretaryTranslationFailed: "Could not translate the Secretary General content.",
    save: "Save settings",
    noImage: "No image",
    changeImage: "Change image",
    uploadImage: "Upload image",
    removeImage: "Remove image",
  },
  es: {
    saved: "Ajustes guardados.",
    selectImageFile: "Selecciona una imagen.",
    signInFirst: "Entra primero en el admin para modificar ajustes globales.",
    title: "Velocidad de carruseles",
    language: "Idioma",
    mode: "Modo",
    autoMode: "Autom\u00e1tico, como ahora",
    manualMode: "Velocidad elegida por el usuario",
    latestReportsSeconds: "Latest reports, segundos por vuelta",
    lowerCarouselSeconds: "Carrusel inferior, segundos por vuelta",
    help: "Cuanto mayor sea el n\u00famero, m\u00e1s lento se mueve. En autom\u00e1tico se mantiene la velocidad actual de la web.",
    secretaryTitle: "Secretario general de IKA",
    secretaryName: "Nombre",
    secretaryRole: "Cargo mostrado",
    secretaryText: "Texto p\u00fablico",
    secretaryPhoto: "Foto",
    secretaryPhotoAlt: "Texto alternativo de la foto",
    translateSecretary: "Traducir todo desde espa\u00f1ol",
    translateSecretaryHelp: "Escribe primero el cargo, texto y texto alternativo en espa\u00f1ol. Este bot\u00f3n generar\u00e1 autom\u00e1ticamente el resto de idiomas.",
    secretaryTranslationNeedsSpanish: "Primero escribe el contenido del Secretario General en espa\u00f1ol.",
    secretaryTranslationReady: "Traducciones generadas. Ahora solo falta guardar ajustes.",
    secretaryTranslationFailed: "No se pudo traducir el Secretario General.",
    save: "Guardar ajustes",
    noImage: "Sin imagen",
    changeImage: "Cambiar imagen",
    uploadImage: "Subir imagen",
    removeImage: "Quitar imagen",
  },
} satisfies Partial<Record<Locale, Record<string, string>>>;

export function getSettingsAdminCopy(locale: Locale) {
  return resolveAdminCopy(locale, dictionaries);
}
